name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Gradle
        run: make -C app build

      - name: Run tests with coverage
        run: ./app/gradlew clean test jacocoTestReport -C app

      - name: Make code coverage report
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.JAVA_PROJECT_72 }}
          JACOCO_SOURCE_PATH: app/src/main/java
        with:
          debug: true
          coverageCommand: make -C app report
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco